### ISSUE TITLE
Arabic Search keywords issue

### ISSUE THREAD

**Issue by Ghorab77** [chukhraiartur/seo-keyword-research-tool#7]
Hello,

Iam trying to run the following query:

seo -q اخبار السعودية -e rq  -dl 1 -gl sa -hl ar -ak XXX

I got the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/seo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/SeoKeywordResearch/cli.py", line 19, in main
    args = parser.parse_args()
  File "/usr/lib/python3.10/argparse.py", line 1848, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.10/argparse.py", line 2604, in error
    self.print_usage(_sys.stderr)
  File "/usr/lib/python3.10/argparse.py", line 2574, in print_usage
    self._print_message(self.format_usage(), file)
  File "/usr/lib/python3.10/argparse.py", line 2540, in format_usage
    return formatter.format_help()
  File "/usr/lib/python3.10/argparse.py", line 295, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.10/argparse.py", line 226, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.10/argparse.py", line 226, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.10/argparse.py", line 350, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError

**Comment by ilyazub** [comment]
@Ghorab77 It worked for me after wrapping the search query with quotes. 

```bash
$ seo -q 'اخبار السعودية' -e rq -dl 1 -gl sa -hl ar --api-key=$SERPAPI_API_KEY
{
  "related_questions": [
    "ماذا تمتلك السعودية؟",
    "ماذا عن السعودية؟",
    "هل السعودية قوة عظمي؟",
    "هل تعتبر السعودية من الدول المتقدمة؟",
    "ما هو قرار السعودية الجديد 2023؟",
    "هل ما يحدث في السعودية من علامات الساعة؟"
  ]
}
Saving data in CSV format...
Data successfully saved to اخبار_السعودية.csv file
```
